### ISSUE TITLE
ERROR in Requirements on Mac OS

### ISSUE THREAD

**Issue by kashkalik** [k4m4/kickthemout#13] opened 2017-01-14 17:37 UTC
Hi Developers, I installed scapy , but when I try to run the script, it gives me the error:

```
 ERROR: Requirements have not been properly satisfied. Please try running:
$ sudo pip install -r requirements.txt
If you still get the same error, please submit an issue here:
https://github.com/k4m4/kickthemout/issues/
```

What could be the problem ? 

Thank you !

**Comment by k4m4** [comment] 2017-01-14 17:38
Hello there. What OS are you running? @kashkalik

**Comment by kashkalik** [comment] 2017-01-14 17:50
I am running MAC os

**Comment by k4m4** [comment] 2017-01-14 18:46
Yes, indeed. There are some issues when running KickThemOut on a Mac, most of which, we can do very little about since its the module we are using that causes the error. Assuming that you have already installed the requirements, I would recommend running the following:
```
$ pip uninstall scapy
$ brew install scapy
```
Please let me know if this works for you. @kashkalik

**Comment by k4m4** [comment] 2017-01-14 20:39
### For **Mac OS X Installations** run the following:

```
Install Requirements:
----------------------
$ sudo pip install pcapy
$ brew install libdnet
$ brew install scapy
--> You might be asked to run some commands after executing the previous step.

Clone Repository:
------------------
$ git clone https://github.com/k4m4/kickthemout.git
$ cd kickthemout/
$ python kickthemout.py
```

**NOTE**: You need to have [**Homebrew**](http://brew.sh/) installed before downloading requirements.

**Comment by k4m4** [comment] 2017-01-14 20:39
Let me know if this works for you please. @kashkalik

**Comment by daniellogvin** [comment] 2017-01-14 22:07
For me stills giving me the error after brew installation 

`name:kickthemout name$ brew install libdnet
Warning: libdnet-1.12 already installed
name:kickthemout name$ brew install scapy
Warning: homebrew/python/scapy-2.3.3 already installed
name:kickthemout name$ cd
name:~ name$ cd Desktop/
name:Desktop name$ git clone https://github.com/k4m4/kickthemout.git
Cloning into 'kickthemout'...
remote: Counting objects: 201, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 201 (delta 8), reused 0 (delta 0), pack-reused 186
Receiving objects: 100% (201/201), 33.58 KiB | 0 bytes/s, done.
Resolving deltas: 100% (106/106), done.
Checking connectivity... done.
name:Desktop name$ cd kickthemout/
name:kickthemout name$ python kickthemout.py 

ERROR: Requirements have not been properly satisfied. Please try running:
	$ sudo pip install -r requirements.txt

If you still get the same error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues/

name:kickthemout name$ `

**Comment by k4m4** [comment] 2017-01-15 01:45
Try uninstalling everything:
```
$ brew uninstall scapy
$ sudo pip uninstall scapy
$ sudo pip uninstall libdnet
$ sudo pip uninstall libdnet
```
Subsequently, run the installation commands again. 

```
$ sudo pip install pcapy
$ brew install libdnet
$ brew install scapy
--> You might be asked to run some commands after executing the previous step.
$ git clone https://github.com/k4m4/kickthemout.git
$ cd kickthemout/
$ python kickthemout.py
```

Let me know how it goes. @daniellogvin

**Comment by SentinelWarren** [comment] 2017-01-15 09:57
@k4m4 `libdnet` is not a python module

**Comment by k4m4** [comment] 2017-01-15 10:03
I do not understand your point. @SentinelWarren

**Comment by k4m4** [comment] 2017-01-15 10:17
That is correct. It was a typo. @SentinelWarren

**Comment by suxxa** [comment] 2017-01-19 15:22
I have the same problem than @kashkalik and @daniellogvin , I have reinstalled all the stuff like you said but it changed nothing.

Here are my versions:

- **macOS Sierra** 10.12.2

- **Python** 2.7

- **Homebrew**  1.1.7
- **libdnet** 1.12

- **pip** 9.0.1
- **scapy** 2.3.3
- **pcapy**0.11.1

Let me know @k4m4 if you want more infos.

Thank you.

**Comment by SentinelWarren** [comment] 2017-01-19 15:42
@suxxa did you try installing `pypcap`?

**Comment by suxxa** [comment] 2017-01-19 15:47
@SentinelWarren Thank you for your time, `pypcap` was not installed. I installed it but the problem is still here.

**Comment by SentinelWarren** [comment] 2017-01-19 15:50
is it the same error requirements not satisfied or your getting another error?

**Comment by suxxa** [comment] 2017-01-19 15:56
It is the same error.

> ERROR: Requirements have not been properly satisfied. Please try running:
> 	$ sudo pip install -r requirements.txt
> 
> If you still get the same error, please submit an issue here:
> 	https://github.com/k4m4/kickthemout/issues

**Comment by SentinelWarren** [comment] 2017-01-19 15:58
ok! try deleting the local clone,the clone it again and repeat the installation steps again

**Comment by suxxa** [comment] 2017-01-19 16:27
I reinstalled all the packages (even pypcap) but nothing changed.

**Comment by daniellogvin** [comment] 2017-01-21 18:59
nothing is working, look:

```ERROR: Requirements have not been properly satisfied. Please try running:
	$ sudo pip install -r requirements.txt

If you still get the same error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Daniels-MacBook-Pro-2:kickthemout daniellogvin$ sudo pip install -r requirements.txt
The directory '/Users/daniellogvin/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/daniellogvin/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: scapy in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 1))

Daniels-MacBook-Pro-2:kickthemout daniellogvin$ 
```

**Comment by SentinelWarren** [comment] 2017-01-21 19:09
@daniellogvin  on mac you should just do 'pip install -r requirements.txt` without sudo

**Comment by daniellogvin** [comment] 2017-01-21 19:09
Requirement already satisfied: scapy in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 1))

**Comment by k4m4** [comment] 2017-01-21 19:09
I don't think that would work. @SentinelWarren

**Comment by daniellogvin** [comment] 2017-01-21 19:10
it's very weird

**Comment by k4m4** [comment] 2017-01-21 19:11
Try running the following (in the exact order): @daniellogvin @suxxa 
```
$ sudo pip uninstall scapy pcapy
$ brew uninstall libdnet scapy
$ sudo pip install pcapy
$ brew install libdnet scapy
```
Let me know how it goes.

**Comment by daniellogvin** [comment] 2017-01-21 19:12
same thing....

**Comment by daniellogvin** [comment] 2017-01-21 19:14
```
Daniels-MacBook-Pro-2:kickthemout daniellogvin$ sudo pip uninstall scapy pcapy
Password:
The directory '/Users/daniellogvin/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling scapy-unknown.version:
  /usr/local/lib/python2.7/site-packages/scapy
  /usr/local/lib/python2.7/site-packages/scapy-unknown.version-py2.7.egg-info
Proceed (y/n)? y
  Successfully uninstalled scapy-unknown.version
Uninstalling pcapy-0.11.1:
  /usr/local/lib/python2.7/site-packages/pcapy-0.11.1-py2.7.egg-info
  /usr/local/lib/python2.7/site-packages/pcapy.so
  /usr/local/share/doc/pcapy/LICENSE
  /usr/local/share/doc/pcapy/README
  /usr/local/share/doc/pcapy/pcapy.html
  /usr/local/tests/96pings.pcap
  /usr/local/tests/pcapytests.py
Proceed (y/n)? y
  Successfully uninstalled pcapy-0.11.1
The directory '/Users/daniellogvin/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Daniels-MacBook-Pro-2:kickthemout daniellogvin$ brew uninstall libdnet scapy
Uninstalling /usr/local/Cellar/libdnet/1.12... (29 files, 389.7K)
Uninstalling /usr/local/Cellar/scapy/2.3.3... (150 files, 2.4M)
Daniels-MacBook-Pro-2:kickthemout daniellogvin$ sudo pip install pcapy
The directory '/Users/daniellogvin/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/daniellogvin/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pcapy
  Downloading pcapy-0.11.1.tar.gz
Installing collected packages: pcapy
  Running setup.py install for pcapy ... done
Successfully installed pcapy-0.11.1
Daniels-MacBook-Pro-2:kickthemout daniellogvin$ brew install libdnet scapy
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/libdnet-1.12.sierra.bottle.2.tar.gz
Already downloaded: /Users/daniellogvin/Library/Caches/Homebrew/libdnet-1.12.sierra.bottle.2.tar.gz
==> Pouring libdnet-1.12.sierra.bottle.2.tar.gz
==> Caveats
Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/daniellogvin/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/daniellogvin/Library/Python/2.7/lib/python/site-packages/homebrew.pth
==> Summary
🍺  /usr/local/Cellar/libdnet/1.12: 29 files, 389.7K
==> Installing scapy from homebrew/python
==> Downloading https://homebrew.bintray.com/bottles-python/scapy-2.3.3.sierra.bottle.tar.gz
Already downloaded: /Users/daniellogvin/Library/Caches/Homebrew/scapy-2.3.3.sierra.bottle.tar.gz
==> Pouring scapy-2.3.3.sierra.bottle.tar.gz
==> Caveats
Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/daniellogvin/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/daniellogvin/Library/Python/2.7/lib/python/site-packages/homebrew.pth
==> Summary
🍺  /usr/local/Cellar/scapy/2.3.3: 150 files, 2.4M
Daniels-MacBook-Pro-2:kickthemout daniellogvin$ sudo python kickthemout.py 

ERROR: Requirements have not been properly satisfied. Please try running:
	$ sudo pip install -r requirements.txt

If you still get the same error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Daniels-MacBook-Pro-2:kickthemout daniellogvin$ 
```

**Comment by k4m4** [comment] 2017-01-21 19:15
You missed some commands scapy asked you to run. Look at the spaces I left on your comment. Run those commands and let me know what happens.

**Comment by k4m4** [comment] 2017-01-21 19:16
It is most likely that the `echo` part wont work. In that case just do `nano /Users/daniellogvin/Library/Python/2.7/lib/python/site-packages/homebrew.pth` and paste the following in the file:
```
import site; 
site.addsitedir("/usr/local/lib/python2.7/site-packages")
```

**Comment by daniellogvin** [comment] 2017-01-21 19:20
added it, and did not work tho... it's very weird, and before that i also tried again the steps you told me to do

**Comment by SentinelWarren** [comment] 2017-01-21 19:22
did you install `python` via brew?

**Comment by k4m4** [comment] 2017-01-21 19:22
Hmm... very odd indeed. You have probably missed something. I cannot imagine anything else, since it definitely has to do with the requirement configuration.

**Comment by daniellogvin** [comment] 2017-01-21 19:23
i believe i did it through brew

**Comment by SentinelWarren** [comment] 2017-01-21 19:25
what is the output of `which python` ?

**Comment by daniellogvin** [comment] 2017-01-21 19:27
/opt/local/bin/python

**Comment by SentinelWarren** [comment] 2017-01-21 19:35
probably you installed `python` via macports since brew installation path is `/usr/local/bin/pyhon` long story short,

try doing the following 

```
brew install python
brew linkapps python
brew link --overwrite python 
```

**Comment by daniellogvin** [comment] 2017-01-21 19:35
that's totally true

**Comment by k4m4** [comment] 2017-01-21 19:36
That's right! Thanks @SentinelWarren for the support ;)
Did it resolve your issue? @daniellogvin

**Comment by daniellogvin** [comment] 2017-01-21 19:36
i'm checking it now

**Comment by daniellogvin** [comment] 2017-01-21 19:38
damn... i did the link and all that stuff and still not working:

```
Daniels-MacBook-Pro-2:kickthemout daniellogvin$ brew install python
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
imagemagick@6                                                             open-mesh

Warning: python-2.7.13 already installed, it's just not linked.
Daniels-MacBook-Pro-2:kickthemout daniellogvin$ brew linkapps python
Linking: /usr/local/opt/python/IDLE.app
Linking: /usr/local/opt/python/Python Launcher.app
Linked 2 apps to /Applications
Daniels-MacBook-Pro-2:kickthemout daniellogvin$ brew link --overwrite python 
Linking /usr/local/Cellar/python/2.7.13... 7999 symlinks created
Daniels-MacBook-Pro-2:kickthemout daniellogvin$ python kickthemout.py 

ERROR: KickThemOut must run as root. Try again with sudo/root:
	$ sudo python kickthemout.py

Daniels-MacBook-Pro-2:kickthemout daniellogvin$ sudo python kickthemout.py 
Password:

ERROR: Requirements have not been properly satisfied. Please try running:
	$ sudo pip install -r requirements.txt

If you still get the same error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Daniels-MacBook-Pro-2:kickthemout daniellogvin$ 
```

**Comment by SentinelWarren** [comment] 2017-01-21 19:40
now try unistalling and reinstalling the modules again

**Comment by daniellogvin** [comment] 2017-01-21 19:41
ok, let me try

**Comment by daniellogvin** [comment] 2017-01-21 19:43
same thing...

**Comment by SentinelWarren** [comment] 2017-01-21 19:52
damn!try doing this again

```
mkdir -p /Users/daniellogvin/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/daniellogvin/Library/Python/2.7/lib/python/site-packages/homebrew.pth
```

**Comment by daniellogvin** [comment] 2017-01-21 19:53
WORKS!!!! PERFECTLY AWESOME!

**Comment by daniellogvin** [comment] 2017-01-21 19:53
don't works at all good, but kinda works

**Comment by daniellogvin** [comment] 2017-01-21 19:54
it has a problem obtaining the gateway

**Comment by SentinelWarren** [comment] 2017-01-21 19:55
run the script with sudo privileges `sudo python kickthemout.py`

**Comment by daniellogvin** [comment] 2017-01-21 20:00
```
Daniels-MacBook-Pro-2:kickthemout daniellogvin$ sudo python kickthemout.py 
Password:

^C
ERROR: Gateway IP could not be obtained. Please enter IP manually.

kickthemout> Enter Gateway IP (e.g. 192.168.1.1): ^CTraceback (most recent call last):
```

**Comment by SentinelWarren** [comment] 2017-01-21 20:03
then it the gateway IP as the script suggests!otherwise i think @k4m4 should take it from here :)!

**Comment by daniellogvin** [comment] 2017-01-21 20:03
awesome, @k4m4 where are you?

**Comment by xdavidhu** [comment] 2017-01-21 22:58
@daniellogvin Just enter your gateway IP manually. It's possible that KickThemOut fails to detect it automatically.

**Comment by daniellogvin** [comment] 2017-01-21 23:14
thanks @xdavidhu !

**Comment by xdavidhu** [comment] 2017-01-21 23:47
You are welcome!
Did you resolve the issue @daniellogvin?

**Comment by daniellogvin** [comment] 2017-01-21 23:48
yes i did! @xdavidhu

**Comment by xdavidhu** [comment] 2017-01-21 23:53
@daniellogvin Happy to hear!
Thank you for submitting the issue!

**Comment by daniellogvin** [comment] 2017-01-21 23:54
@xdavidhu thank you and thank you to everybody for helping to fix this issue

**Comment by k4m4** [comment] 2017-01-22 00:22
Hello again @daniellogvin .
Sorry for the delayed response.
Glad to hear your issue has been resolved.

**Closed by k4m4** 2017-01-22 00:22 UTC
Labels: enhancement, question
