### ISSUE TITLE
i cant run kickthemout.py in any way. Help!

### ISSUE THREAD

**Issue by olekmorawski** [k4m4/kickthemout#255] opened 2018-02-20 09:43 UTC
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **Kali Linux**: 
- **python 2.7.14**: 
- **idk**: 
- **lastest**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **im trying to start the kickthemout.py but i get something like this:

root@Kali:~/Desktop/kickthemout# sudo python3 kickthemout.py
ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.
If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues
Details: No module named 'scapy'

and if i try installing the requirements.txt i get this:

Requirement already satisfied: scapy-python3 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: python-nmap in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: netifaces in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 3))

i have tried all of these commands:
- sudo -H python3 -m pip3 install -r requirements.txt
- sudo -H pip3 install -r requirements.txt
- sudo python kicktehmout.py
- sudo python3 kickthemout.py
- sudo python2 kickthemout.py

im trying to fix this for like 4 hours right now...
can somebody help  me maybe?

**:

**Comment by k4m4** [comment] 2018-02-20 10:04
Hi there @olekmorawski. What error do you get when running `sudo -H python3 -m pip3 install -r requirements.txt`?

**Comment by olekmorawski** [comment] 2018-02-20 16:51
@k4m4 i get: no module named pip3

**Comment by k4m4** [comment] 2018-02-20 17:17
Sorry, I meant `sudo -H python3 -m pip install -r requirements.txt`.

**Comment by olekmorawski** [comment] 2018-02-20 17:44
@k4m4 


cmd:

root@Kali:~/Desktop/kickthemout# sudo -H python3 -m pip install -r requirements.txt
Requirement already satisfied: scapy-python3 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: python-nmap in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: netifaces in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 3))
root@Kali:~/Desktop/kickthemout# sudo apt-get install python3-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version (9.0.1-2).
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.

**Comment by k4m4** [comment] 2018-02-20 18:14
Do you get the same error if you run `sudo python3 kickthemout.py`?

**Comment by olekmorawski** [comment] 2018-02-20 18:17
@k4m4  still says no module named scapy

**Comment by lchngthewrld** [comment] 2018-02-21 12:46
@k4m4 hello ! i was searching for some help thought was the only one having those issues.. and i ended up here , i have the same exactly error 

/kickthemout# sudo python3 kickthemout.py 

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: No module named 'scapy'

**Comment by Syonagar** [comment] 2018-02-22 16:01
root@debian:~/Documents/kickthemout# sudo -H python3 -m pip3 install -r requirements.txt
/usr/bin/python3: No module named pip3

HELP ME

**Comment by k4m4** [comment] 2018-03-03 14:35
This has developed into a duplicate of Issue #249. Please refer to #249 for more information on this. Thanks!

**Closed by k4m4** 2018-03-03 14:35 UTC
Labels: question

**Comment by idilerwin** [comment] 2018-09-06 03:50
pleasee help..

Scanning your network, hang on...

ERROR: Network scanning failed. Please check your requirements configuration.

If you still cannot resolve this error, please submit an issue here:
        https://github.com/k4m4/kickthemout/issues

Details: module 'nmap' has no attribute 'PortScanner'

**Comment by sahildhiman1997** [comment] 2018-10-21 14:16
how to defend from kickthemout?

**Comment by alfaridzf100** [comment] 2019-10-20 00:42
try this command :
pip3 install scapy
