### ISSUE TITLE
ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.....this is the issue

### ISSUE THREAD

**Issue by biniya** [k4m4/kickthemout#270] opened 2018-03-11 08:09 UTC
## Checklist for submitting an issue to `KickThemOut`:

- [ ] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [ ] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [ ] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Scapy version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**:

**Comment by k4m4** [comment] 2018-04-15 10:53
Hi there. This issue appears to be a duplicate of previously solved, closed issues. Please refer to those similar issues and if you still cannot solve your dependency problem reopen this one. Thanks!

**Closed by k4m4** 2018-04-15 10:53 UTC
Labels: duplicate, question
