### ISSUE TITLE
IndentationError: expected an indented block

### ISSUE THREAD

**Issue by TNT5788** [k4m4/kickthemout#9] opened 2017-01-11 00:36 UTC
Hello, i'm having a error when i'm typing: python kickthemout.py

```
File "kickthemout.py", line 239
    print("\n{0}ERROR: Gateway IP could not be obtained. Please enter IP manually.{2}\n").format(RED, END)
        ^
IndentationError: expected an indented block
```
Could you please help me ?

Thanks for your help and that tool.

**Comment by DarkForestIT** [comment] 2017-01-11 05:03
@TNT5788 

`except:
        print("\n{0}ERROR: Gateway IP could not be obtained. Please enter IP manually.{2}\n").format(RED, END)
        header = ('{0}kickthemout{1}> {2}Enter Gateway IP {3}(e.g. 192.168.1.1): '.format(BLUE, WHITE, RED, END))
        gatewayIP = raw_input(header)
        return gatewayIP`

Edit the kickthemout.py file by adding 4 spaces on lines 239-242 to indent the statements properly into the except clause like above

**Comment by xdavidhu** [comment] 2017-01-11 06:15
Thanks for your report, the issue is now fixed.

**Comment by TNT5788** [comment] 2017-01-12 21:58
Thanks, it's now working.

**Closed** 2017-01-12 22:00 UTC
Labels: bug
