### ISSUE TITLE
ERROR: It seems that you are offline. Please check your internet connection.

### ISSUE THREAD

**Issue by nikior9** [k4m4/kickthemout#306] opened 2018-06-12 23:21 UTC
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**: macOS Sierra 10.12.6
- **Python version**: 3.6
- **Scapy version**: 2.4
- **Nmap version**: 7.70
- **Link of [Gist](https://gist.github.com/)**: https://gist.github.com/nikior9/e11cbea186b9746caebd16921346486b

```
blank-2:kickthemout Mac$ sudo python3 kickthemout.py

ERROR: It seems that you are offline. Please check your internet connection.

blank-2:kickthemout Mac$ ping -c 2 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: icmp_seq=0 ttl=56 time=25.227 ms
64 bytes from 8.8.8.8: icmp_seq=1 ttl=56 time=24.212 ms

--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 24.212/24.720/25.227/0.507 ms
```
- **Description**: 

> ERROR: It seems that you are offline. Please check your internet connection.

Google opens perfectly. Changing google to any other website didn't help

**Comment by MrdotSpock** [comment] 2018-06-20 20:17
You can fix it using a little hack. 

1. Open kickthemout.py
2. Find this line of code `def checkInternetConnection():`. In my editor it's line 128
3. Replace function body with this `return True`. (delete everything from line 129 to line 135)

Note: This is just a temporary fix and it will crash when you are not connected.
The problem is probably with function urlopen.

Hope it helps

**Comment by nikior9** [comment] 2018-06-21 17:04
Tried it before, didn't help. It's like loading but infinitely and uses a lot of CPU

**Comment by k4m4** [comment] 2018-06-25 13:05
Hi there. Thank you for bringing this to our attention; I will try to reproduce this issue locally. For now, you can delete lines 738-745:
```
    try:
        if checkInternetConnection():
       ...
        shutdown()
``` in order for the script to run normally. Thanks again.

**Comment by k4m4** [comment] 2018-11-07 08:20
This issue should be resolved in PR #341. If not, please don't hesitate to re-open it. Thanks!

**Closed by k4m4** 2018-11-07 08:20 UTC

**Comment by N0va1** [comment] 2019-04-11 19:55
Hello Guysss :)

# make sure there is an internet connection
def checkInternetConnection():
    try:
        urlopen('https://github.com', timeout=0)
        return False
    except URLError as err:
        return True
    except KeyboardInterrupt:
        shutdown()

CHANGE

**Comment by Flori201** [comment] 2019-04-23 12:22
> Hello Guysss :)
> 
> # make sure there is an internet connection
> def checkInternetConnection():
> try:
> urlopen('https://github.com', timeout=0)
> return False
> except URLError as err:
> return True
> except KeyboardInterrupt:
> shutdown()
> 
> CHANGE

can you video

**Comment by guinevereperez** [comment] 2019-05-12 15:24
> You can fix it using a little hack.
> 
> 1. Open kickthemout.py
> 2. Find this line of code `def checkInternetConnection():`. In my editor it's line 128
> 3. Replace function body with this `return True`. (delete everything from line 129 to line 135)
> 
> Note: This is just a temporary fix and it should be solved in better way.
> The problem is probably with function urlopen.
> 
> Hope this helps

This fixed the problem for me thank you!

**Comment by Upanori7** [comment] 2019-11-16 05:19
> You can fix it using a little hack.
> 
> 1. Open kickthemout.py
> 2. Find this line of code `def checkInternetConnection():`. In my editor it's line 128
> 3. Replace function body with this `return True`. (delete everything from line 129 to line 135)
> 
> Note: This is just a temporary fix and it should be solved in better way.
> The problem is probably with function urlopen.
> 
> Hope this helps

l cant run any command like those aboved, this is the output results : 

root@localhost:~/kickthemout#bash kickthemout.py
kickthemout.py: line 8:
Copyright (C) 2017-18 Nikolaos Kamarinakis (nikolaskam@gmail.com) & David Schütz (xdavid@protonmail.com)
See License at nikolaskama.me (https://nikolaskama.me/kickthemoutproject)
: No such file or directory
kickthemout.py: line 10: import: command not found
kickthemout.py: line 11: from: command not found
kickthemout.py: line 12: BLUE,: command not found
kickthemout.py: line 14: try:: command not found
kickthemout.py: line 16: syntax error near unexpected token `!='
kickthemout.py: line 16: `    if os.geteuid() != 0



l am using "bash" command instead "Open"
l am using Termux and its always end up with : its seems you are offline. Please check your internet connection


Please help me , 
Does it any kind of way of command how to edit/configure file "kickthemout.py
